name: uas_made_2
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  firebase_database: ^10.2.3
  logger: ^1.1.0
  http: ^1.1.0
  flutter:
     sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
