// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2z_02gQyoPDwfO2ggynT69O8yYC2B8_I',
    appId: '1:1088812474086:web:4f5b191ccb02052b47e527',
    messagingSenderId: '1088812474086',
    projectId: 'uasmade2',
    authDomain: 'uasmade2.firebaseapp.com',
    databaseURL: 'https://uasmade2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'uasmade2.appspot.com',
    measurementId: 'G-8MMC17VLQH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVXkHN3ss55ln4PoXkXHfFUc0aNClNJW0',
    appId: '1:1088812474086:android:c84da76e336d032147e527',
    messagingSenderId: '1088812474086',
    projectId: 'uasmade2',
    storageBucket: 'uasmade2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJVANX5BIMBLOrN2W1tyyrQ3TpmhSmvNI',
    appId: '1:1088812474086:ios:146959dd1ecf4a7647e527',
    messagingSenderId: '1088812474086',
    projectId: 'uasmade2',
    storageBucket: 'uasmade2.appspot.com',
    iosClientId: '1088812474086-3e426g718o6k5bu9vb7343stc376b193.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasMade2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJVANX5BIMBLOrN2W1tyyrQ3TpmhSmvNI',
    appId: '1:1088812474086:ios:9f53cb0d8a255ccf47e527',
    messagingSenderId: '1088812474086',
    projectId: 'uasmade2',
    storageBucket: 'uasmade2.appspot.com',
    iosClientId: '1088812474086-pu1djlq7jjguprqog73fmebsa32r4s1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.uasMade2.RunnerTests',
  );
}
